#!/bin/bash

# WIP.

number=9
points=0

parse_attributes() {
while [[ $# > 0 ]] ; do
  case "$1" in
    -n|--number) 
      number=${2}
      shift
      ;;
  esac
  shift
done
}
parse_attributes "$@"

for i in $(seq 1 $number); do

  if [ "$i" == "1" ]; then
    echo "What is π in degrees?"
    echo "        –"
    echo "        4"
    echo ""
    read user_input
    if [ "$user_input" == "45" ]; then
      echo "Correct!"
    else
      echo "Inorrect. It's actually 45."
    fi
  fi

done

