#!/bin/bash

points=0
if [ ! -f ~/.sub_high_score ]; then
  echo "0" > ~/.sub_high_score
  high_score=0
else
  high_score=$(cat ~/.sub_high_score)
fi

for i in {1..10}
do
  rone=""
  rtwo=""
  while [ "$rone" == "$rtwo" ]; do
    rone=$(( $RANDOM % 9 + 1 )) # 1-10
    rtwo=$(( $RANDOM % (10 - $rone) + $rone )) # a number higher
  done
  
  rone=$(($rone + 10))
  answ=$(($rone - $rtwo))
  echo "$rone - $rtwo"
  read user_input

  if [ "$user_input" == "$answ" ]; then
    echo "Correct!"
    points=$(($points + 10))
  else
    points=$(($points - 10))
  fi
done

score=$(($points - $SECONDS))

if [ $score -gt $high_score ]; then
  high_score=$score
  echo "$high_score" > ~/.sub_high_score
  echo "You set a new high score of $high_score"
fi

echo "Your score is $score. The High score is $high_score"
